### ISSUE TITLE
Nullable callback cause error

### ISSUE THREAD

**Issue by CeceWall** [notenoughneon/typed-promisify#6]
Some library declare a function like 

`get(sql: string, params: any, callback?: (err: Error, row: any) => void): Database;
`

This would make an error when tp library declare callback function couldn't be null

`
export function promisify<A, A2, T>(f: (arg: A, arg2: A2, cb: (err: any, res: T) => void) => void, thisContext?: any): (arg: A, arg2: A2) => Promise<T>;
`

**Comment by CeceWall** [comment]
Sorry, it happened because the library has multiple get definations
`

    get(sql: string, callback?: (err: Error, row: any) => void): Database;
    get(sql: string, params: any, callback?: (err: Error, row: any) => void): Database;
    get(sql: string, ...params: any[]): Database;

`
Please close this issue, and could you give me any help to solve this problem?

**Comment by notenoughneon** [comment]
What if you make a wrapper function for `get()` with just one signature, so it always expects the callback?
